// Generated by GraphWalker (http://www.graphwalker.org)
package com.techelevator;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "Vending-Machine_HFSM_semFim.json")
public interface menu_compra {

    @Vertex()
    void menu_compra();
    
    @Edge()
    void e_insere_quantia_invalida();

    @Vertex()
    void espera_produto();

    @Vertex()
    void libera_produto();

    @Edge()
    void e_produto_indisponivel();

    @Vertex()
    void verifica_saldo();

    @Edge()
    void e_escolhe_opcao2();

    @Edge()
    void e_escolhe_opcao3();

    @Edge()
    void e_insere_codigo_incorreto();

    @Edge()
    void e_escolhe_opcao1();

    @Vertex()
    void menu_principal();

    @Vertex()
    void espera_moeda();

    @Edge()
    void e_insere_codigo();

    @Edge()
    void e_produto_disponivel();

    @Edge()
    void e_verifica_saldo();

    @Vertex()
    void verifica_disponibilidade();

    @Edge()
    void e_insere_quantia();

    @Edge()
    void e_devolve_troco();

    @Edge()
    void e_produtto_liberado();

    @Vertex()
    void finaliza_acao();
}
