// Generated by GraphWalker (http://www.graphwalker.org)
package com.techelevator;
import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "Vending-Machine_HFSM_AddProduto.json")
public interface menu_add_produto {

    @Edge()
    void e_qtd_incorreta();

    @Edge()
    void e_entra_menuPrincipal();

    @Edge()
    void e_escolhe_opcao2();

    @Vertex()
    void add_produto();

    @Edge()
    void e_insere_codigo_incorreto();

    @Edge()
    void e_escolhe_opcao1();

    @Vertex()
    void add_finaliza_acao();

    @Vertex()
    void atualiza_quantidade();

    @Vertex()
    void menu_principal();

    @Edge()
    void e_insere_codigo();

    @Vertex()
    void espera_quantidade();

    @Edge()
    void e_atualiza_qnt();

    @Vertex()
    void add_espera_produto();

    @Edge()
    void e_qtd_correta();
}
